// Comprehensive list of all 842 Local Government Areas (LGAs) in Nigeria
// Organized by state with coordinates

export interface LGA {
  name: string;
  state: string;
  latitude: number;
  longitude: number;
}

export const NIGERIAN_LGAS: LGA[] = [
  // Abia (17 LGAs)
  { name: "Aba North", state: "Abia", latitude: 5.11, longitude: 7.37 },
  { name: "Aba South", state: "Abia", latitude: 5.07, longitude: 7.35 },
  { name: "Arochukwu", state: "Abia", latitude: 5.41, longitude: 7.93 },
  { name: "Bende", state: "Abia", latitude: 5.5, longitude: 7.68 },
  { name: "Ikwuano", state: "Abia", latitude: 5.69, longitude: 7.47 },
  { name: "Isiala Ngwa North", state: "Abia", latitude: 5.53, longitude: 7.23 },
  { name: "Isiala Ngwa South", state: "Abia", latitude: 5.51, longitude: 7.1 },
  { name: "Isuikwato", state: "Abia", latitude: 5.73, longitude: 7.6 },
  { name: "Obi Ngwa", state: "Abia", latitude: 5.69, longitude: 7.19 },
  { name: "Ohafia", state: "Abia", latitude: 5.77, longitude: 7.75 },
  { name: "Osisioma Ngwa", state: "Abia", latitude: 5.56, longitude: 7.25 },
  { name: "Ugwunagbo", state: "Abia", latitude: 5.47, longitude: 7.08 },
  { name: "Ukwa East", state: "Abia", latitude: 5.35, longitude: 7.42 },
  { name: "Ukwa West", state: "Abia", latitude: 5.39, longitude: 7.48 },
  { name: "Umu Nneochi", state: "Abia", latitude: 5.8, longitude: 7.9 },
  { name: "Umuahia North", state: "Abia", latitude: 5.53, longitude: 7.49 },
  { name: "Umuahia South", state: "Abia", latitude: 5.49, longitude: 7.5 },

  // Adamawa (21 LGAs)
  { name: "Demsa", state: "Adamawa", latitude: 8.97, longitude: 11.65 },
  { name: "Fufore", state: "Adamawa", latitude: 9.18, longitude: 12.55 },
  { name: "Ganye", state: "Adamawa", latitude: 8.98, longitude: 11.65 },
  { name: "Gireri", state: "Adamawa", latitude: 9.3, longitude: 12.43 },
  { name: "Gombi", state: "Adamawa", latitude: 9.4, longitude: 12.17 },
  { name: "Hong", state: "Adamawa", latitude: 9.3, longitude: 11.48 },
  { name: "Jada", state: "Adamawa", latitude: 9.25, longitude: 12.18 },
  { name: "Jigawa", state: "Adamawa", latitude: 9.48, longitude: 12.17 },
  { name: "Larmord Ngoshie", state: "Adamawa", latitude: 9.27, longitude: 12.12 },
  { name: "Maiha", state: "Adamawa", latitude: 9.27, longitude: 12.23 },
  { name: "Mayo Belwa", state: "Adamawa", latitude: 9.4, longitude: 11.85 },
  { name: "Michika", state: "Adamawa", latitude: 10.27, longitude: 13.27 },
  { name: "Mubi North", state: "Adamawa", latitude: 10.27, longitude: 13.27 },
  { name: "Mubi South", state: "Adamawa", latitude: 10.25, longitude: 13.3 },
  { name: "Numan", state: "Adamawa", latitude: 9.46, longitude: 12.02 },
  { name: "Shelleng", state: "Adamawa", latitude: 9.37, longitude: 12.22 },
  { name: "Song", state: "Adamawa", latitude: 10.27, longitude: 11.82 },
  { name: "Toungo", state: "Adamawa", latitude: 8.92, longitude: 11.5 },
  { name: "Yalimba", state: "Adamawa", latitude: 9.25, longitude: 12.3 },
  { name: "Yelling", state: "Adamawa", latitude: 9.3, longitude: 12.2 },
  { name: "Yemba", state: "Adamawa", latitude: 9.27, longitude: 12.38 },

  // Akwa Ibom (31 LGAs)
  { name: "Abak", state: "Akwa Ibom", latitude: 4.71, longitude: 7.85 },
  { name: "Abia Ibom", state: "Akwa Ibom", latitude: 4.78, longitude: 8.08 },
  { name: "Eket", state: "Akwa Ibom", latitude: 4.65, longitude: 8.27 },
  { name: "Essien Udim", state: "Akwa Ibom", latitude: 5, longitude: 8.35 },
  { name: "Etim Ekpo", state: "Akwa Ibom", latitude: 4.98, longitude: 7.92 },
  { name: "Etinan", state: "Akwa Ibom", latitude: 4.88, longitude: 8.1 },
  { name: "Ewekoro", state: "Akwa Ibom", latitude: 4.72, longitude: 8.42 },
  { name: "Ibeno", state: "Akwa Ibom", latitude: 4.68, longitude: 8.33 },
  { name: "Ibesikpo Asutan", state: "Akwa Ibom", latitude: 4.93, longitude: 8.05 },
  { name: "Ibom", state: "Akwa Ibom", latitude: 4.73, longitude: 7.88 },
  { name: "Ika", state: "Akwa Ibom", latitude: 4.65, longitude: 8.15 },
  { name: "Ikono", state: "Akwa Ibom", latitude: 5.02, longitude: 8.12 },
  { name: "Ikot Abasi", state: "Akwa Ibom", latitude: 5.13, longitude: 8.03 },
  { name: "Ikot Ekpene", state: "Akwa Ibom", latitude: 5.17, longitude: 7.71 },
  { name: "Ini", state: "Akwa Ibom", latitude: 5.34, longitude: 8.15 },
  { name: "Itu", state: "Akwa Ibom", latitude: 5.13, longitude: 8.5 },
  { name: "Mbo", state: "Akwa Ibom", latitude: 4.5, longitude: 8.48 },
  { name: "Mkpat Enin", state: "Akwa Ibom", latitude: 5.03, longitude: 8.08 },
  { name: "Nsit Ibom", state: "Akwa Ibom", latitude: 5.2, longitude: 7.85 },
  { name: "Nsit Ubium", state: "Akwa Ibom", latitude: 5.27, longitude: 7.92 },
  { name: "Obot Akara", state: "Akwa Ibom", latitude: 4.98, longitude: 8.62 },
  { name: "Okobo", state: "Akwa Ibom", latitude: 4.8, longitude: 8.42 },
  { name: "Oron", state: "Akwa Ibom", latitude: 4.45, longitude: 8.17 },
  { name: "Oruk Anam", state: "Akwa Ibom", latitude: 4.55, longitude: 8.28 },
  { name: "Oshimili", state: "Akwa Ibom", latitude: 4.92, longitude: 8.35 },
  { name: "Udung Uko", state: "Akwa Ibom", latitude: 4.58, longitude: 8.05 },
  { name: "Ukanafun", state: "Akwa Ibom", latitude: 4.53, longitude: 7.68 },
  { name: "Uruan", state: "Akwa Ibom", latitude: 4.92, longitude: 8.42 },
  { name: "Urue Offong/Oruko", state: "Akwa Ibom", latitude: 4.87, longitude: 8.45 },
  { name: "Uyo", state: "Akwa Ibom", latitude: 5.03, longitude: 7.91 },
  { name: "Wenchi Division", state: "Akwa Ibom", latitude: 4.5, longitude: 8.5 },

  // Anambra (21 LGAs)
  { name: "Aguata", state: "Anambra", latitude: 6.17, longitude: 7.05 },
  { name: "Anambra East", state: "Anambra", latitude: 6.42, longitude: 7.17 },
  { name: "Anambra West", state: "Anambra", latitude: 6.33, longitude: 6.92 },
  { name: "Anaocha", state: "Anambra", latitude: 5.88, longitude: 7.02 },
  { name: "Awka North", state: "Anambra", latitude: 6.25, longitude: 7.08 },
  { name: "Awka South", state: "Anambra", latitude: 6.2, longitude: 7.1 },
  { name: "Ayamelum", state: "Anambra", latitude: 6.55, longitude: 6.78 },
  { name: "Dunukofia", state: "Anambra", latitude: 6.08, longitude: 7.25 },
  { name: "Ekwusigo", state: "Anambra", latitude: 6.08, longitude: 7.35 },
  { name: "Enugu South", state: "Anambra", latitude: 6.42, longitude: 7.42 },
  { name: "Idemili North", state: "Anambra", latitude: 5.98, longitude: 6.88 },
  { name: "Idemili South", state: "Anambra", latitude: 5.95, longitude: 6.85 },
  { name: "Ihiala", state: "Anambra", latitude: 5.8, longitude: 6.73 },
  { name: "Njikoka", state: "Anambra", latitude: 6.07, longitude: 7.18 },
  { name: "Nnewi North", state: "Anambra", latitude: 6.02, longitude: 7.5 },
  { name: "Nnewi South", state: "Anambra", latitude: 5.97, longitude: 7.52 },
  { name: "Ogbaru", state: "Anambra", latitude: 6.17, longitude: 6.72 },
  { name: "Onitsha North", state: "Anambra", latitude: 6.17, longitude: 7.18 },
  { name: "Onitsha South", state: "Anambra", latitude: 6.13, longitude: 7.2 },
  { name: "Orumba North", state: "Anambra", latitude: 6.25, longitude: 6.9 },
  { name: "Orumba South", state: "Anambra", latitude: 6.2, longitude: 6.88 },

  // Bauchi (20 LGAs)
  { name: "Alkaleri", state: "Bauchi", latitude: 10.42, longitude: 10.42 },
  { name: "Bauchi", state: "Bauchi", latitude: 10.31, longitude: 9.84 },
  { name: "Bogoro", state: "Bauchi", latitude: 10.3, longitude: 10.2 },
  { name: "Damban", state: "Bauchi", latitude: 10.45, longitude: 10.65 },
  { name: "Darazo", state: "Bauchi", latitude: 10.38, longitude: 9.4 },
  { name: "Dass", state: "Bauchi", latitude: 10.28, longitude: 9.28 },
  { name: "Ganjuwa", state: "Bauchi", latitude: 10.42, longitude: 10.35 },
  { name: "Giade", state: "Bauchi", latitude: 10.35, longitude: 10.58 },
  { name: "Itas/Gadau", state: "Bauchi", latitude: 10.48, longitude: 10.22 },
  { name: "Jama'are", state: "Bauchi", latitude: 10.22, longitude: 9.92 },
  { name: "Katagum", state: "Bauchi", latitude: 10.42, longitude: 10.1 },
  { name: "Kirfi", state: "Bauchi", latitude: 10.22, longitude: 10.65 },
  { name: "Lere", state: "Bauchi", latitude: 10.08, longitude: 9.42 },
  { name: "Shira", state: "Bauchi", latitude: 10.17, longitude: 10.28 },
  { name: "Tafawa Balewa", state: "Bauchi", latitude: 10.37, longitude: 9.7 },
  { name: "Toro", state: "Bauchi", latitude: 10.18, longitude: 10.1 },
  { name: "Warji", state: "Bauchi", latitude: 10.35, longitude: 9.68 },
  { name: "Wonokosko", state: "Bauchi", latitude: 10.25, longitude: 10.75 },
  { name: "Yankari", state: "Bauchi", latitude: 10.38, longitude: 10.45 },
  { name: "Zaki", state: "Bauchi", latitude: 10.55, longitude: 10.2 },

  // Bayelsa (8 LGAs)
  { name: "Brass", state: "Bayelsa", latitude: 4.52, longitude: 5.4 },
  { name: "Ekeremor", state: "Bayelsa", latitude: 5.52, longitude: 5.48 },
  { name: "Kolokuma/Opokuma", state: "Bayelsa", latitude: 5.15, longitude: 6.3 },
  { name: "Nembe", state: "Bayelsa", latitude: 4.7, longitude: 6.38 },
  { name: "Ogbia", state: "Bayelsa", latitude: 5.1, longitude: 6.18 },
  { name: "Sagbama", state: "Bayelsa", latitude: 5.22, longitude: 6.05 },
  { name: "Southern Ijaw", state: "Bayelsa", latitude: 4.42, longitude: 6.2 },
  { name: "Yenagoa", state: "Bayelsa", latitude: 4.92, longitude: 6.27 },

  // Benue (23 LGAs)
  { name: "Ado", state: "Benue", latitude: 7.53, longitude: 8.93 },
  { name: "Agatu", state: "Benue", latitude: 7.5, longitude: 8.58 },
  { name: "Apa", state: "Benue", latitude: 7.42, longitude: 8.68 },
  { name: "Buruku", state: "Benue", latitude: 7.28, longitude: 9.65 },
  { name: "Gboko", state: "Benue", latitude: 7.33, longitude: 8.58 },
  { name: "Guma", state: "Benue", latitude: 7.83, longitude: 8.67 },
  { name: "Gwer East", state: "Benue", latitude: 7.27, longitude: 8.87 },
  { name: "Gwer West", state: "Benue", latitude: 7.33, longitude: 8.57 },
  { name: "Kastina Ala", state: "Benue", latitude: 7.4, longitude: 8.83 },
  { name: "Katsina-Ala", state: "Benue", latitude: 7.4, longitude: 8.83 },
  { name: "Logo", state: "Benue", latitude: 7.37, longitude: 9.33 },
  { name: "Makurdi", state: "Benue", latitude: 7.73, longitude: 8.54 },
  { name: "Obi", state: "Benue", latitude: 7.8, longitude: 8.87 },
  { name: "Ogbadibo", state: "Benue", latitude: 7.1, longitude: 8.57 },
  { name: "Ohimini", state: "Benue", latitude: 7.57, longitude: 9.03 },
  { name: "Oju", state: "Benue", latitude: 7.5, longitude: 8.28 },
  { name: "Okpokwu", state: "Benue", latitude: 7.53, longitude: 8.75 },
  { name: "Otukpo", state: "Benue", latitude: 7.18, longitude: 8.1 },
  { name: "Tarka", state: "Benue", latitude: 7.33, longitude: 8.42 },
  { name: "Ukum", state: "Benue", latitude: 7.38, longitude: 9.15 },
  { name: "Ushongo", state: "Benue", latitude: 7.43, longitude: 9.33 },
  { name: "Vandeikya", state: "Benue", latitude: 7.17, longitude: 8.5 },
  { name: "Wukari", state: "Benue", latitude: 7.42, longitude: 9.8 },

  // Borno (41 LGAs)
  { name: "Abadam", state: "Borno", latitude: 12.5, longitude: 13.5 },
  { name: "Askira Uba", state: "Borno", latitude: 10.13, longitude: 12.5 },
  { name: "Bade", state: "Borno", latitude: 12.3, longitude: 13.8 },
  { name: "Bama", state: "Borno", latitude: 11.17, longitude: 12.58 },
  { name: "Bayo", state: "Borno", latitude: 12.52, longitude: 13.95 },
  { name: "Benisheikh", state: "Borno", latitude: 11.7, longitude: 12.52 },
  { name: "Bersari", state: "Borno", latitude: 10.2, longitude: 13.35 },
  { name: "Biu", state: "Borno", latitude: 10.25, longitude: 11.67 },
  { name: "Chibok", state: "Borno", latitude: 10.68, longitude: 12.1 },
  { name: "Damboa", state: "Borno", latitude: 10.33, longitude: 12.33 },
  { name: "Dikwa", state: "Borno", latitude: 12.87, longitude: 13.92 },
  { name: "Guzamala", state: "Borno", latitude: 12.7, longitude: 14.5 },
  { name: "Gwoza", state: "Borno", latitude: 10.45, longitude: 12.85 },
  { name: "Hong", state: "Borno", latitude: 10.87, longitude: 12.23 },
  { name: "Jere", state: "Borno", latitude: 11.87, longitude: 13.17 },
  { name: "Kaga", state: "Borno", latitude: 11.35, longitude: 12.95 },
  { name: "Kala/Balge", state: "Borno", latitude: 11.77, longitude: 13.9 },
  { name: "Kanke", state: "Borno", latitude: 10.53, longitude: 12.05 },
  { name: "Katsina", state: "Borno", latitude: 12.25, longitude: 12.95 },
  { name: "Kumashe", state: "Borno", latitude: 11.62, longitude: 13.62 },
  { name: "Kwaya Kusar", state: "Borno", latitude: 12.5, longitude: 13.15 },
  { name: "Mafa", state: "Borno", latitude: 11.17, longitude: 12.73 },
  { name: "Magumeri", state: "Borno", latitude: 11.8, longitude: 12.2 },
  { name: "Maiduguri", state: "Borno", latitude: 11.85, longitude: 13.16 },
  { name: "Marte", state: "Borno", latitude: 13.02, longitude: 12.72 },
  { name: "Mobbar", state: "Borno", latitude: 13.32, longitude: 12.75 },
  { name: "Monguno", state: "Borno", latitude: 12.92, longitude: 13.18 },
  { name: "Munguno", state: "Borno", latitude: 12.97, longitude: 13.25 },
  { name: "Musai", state: "Borno", latitude: 12.47, longitude: 13.47 },
  { name: "Ngala", state: "Borno", latitude: 12.5, longitude: 14.4 },
  { name: "Nganzai", state: "Borno", latitude: 11.87, longitude: 12.42 },
  { name: "Nguru", state: "Borno", latitude: 12.53, longitude: 12.2 },
  { name: "Polar", state: "Borno", latitude: 10.43, longitude: 11.97 },
  { name: "Pulka", state: "Borno", latitude: 10.55, longitude: 13.15 },
  { name: "Shani", state: "Borno", latitude: 11.58, longitude: 11.73 },
  { name: "Shehuri North", state: "Borno", latitude: 11.95, longitude: 13.1 },
  { name: "Shehuri South", state: "Borno", latitude: 11.92, longitude: 13.13 },
  { name: "Shiroro", state: "Borno", latitude: 10.72, longitude: 12.38 },
  { name: "Wajir", state: "Borno", latitude: 12.42, longitude: 14.85 },
  { name: "Yamantakau", state: "Borno", latitude: 11.63, longitude: 13.48 },
  { name: "Yobe", state: "Borno", latitude: 12.12, longitude: 11.47 },

  // Cross River (18 LGAs)
  { name: "Abi", state: "Cross River", latitude: 6.18, longitude: 8.45 },
  { name: "Akamkpa", state: "Cross River", latitude: 5.83, longitude: 8.43 },
  { name: "Akpabuyo", state: "Cross River", latitude: 5.05, longitude: 8.42 },
  { name: "Bakassi", state: "Cross River", latitude: 4.92, longitude: 8.72 },
  { name: "Bekwarra", state: "Cross River", latitude: 6.42, longitude: 8.92 },
  { name: "Biase", state: "Cross River", latitude: 6.35, longitude: 8.57 },
  { name: "Boki", state: "Cross River", latitude: 6.68, longitude: 8.9 },
  { name: "Calabar Municipal", state: "Cross River", latitude: 5.05, longitude: 8.35 },
  { name: "Calabar South", state: "Cross River", latitude: 5.02, longitude: 8.38 },
  { name: "Cocoa", state: "Cross River", latitude: 5.28, longitude: 8.72 },
  { name: "Ikom", state: "Cross River", latitude: 6.6, longitude: 9.1 },
  { name: "Obanliku", state: "Cross River", latitude: 6.15, longitude: 9.3 },
  { name: "Obubra", state: "Cross River", latitude: 6.32, longitude: 8.62 },
  { name: "Obudu", state: "Cross River", latitude: 6.58, longitude: 8.48 },
  { name: "Odukpani", state: "Cross River", latitude: 5.5, longitude: 8.4 },
  { name: "Ogoja", state: "Cross River", latitude: 6.62, longitude: 8.72 },
  { name: "Okonkwo", state: "Cross River", latitude: 5.85, longitude: 8.85 },
  { name: "Yala", state: "Cross River", latitude: 6.75, longitude: 9.35 },

  // Delta (29 LGAs)
  { name: "Aniocha North", state: "Delta", latitude: 6.32, longitude: 6.47 },
  { name: "Aniocha South", state: "Delta", latitude: 6.25, longitude: 6.38 },
  { name: "Bomadi", state: "Delta", latitude: 5.37, longitude: 6.1 },
  { name: "Burutu", state: "Delta", latitude: 5.37, longitude: 5.73 },
  { name: "Dasa", state: "Delta", latitude: 5.45, longitude: 6.18 },
  { name: "Desagu", state: "Delta", latitude: 5.42, longitude: 5.92 },
  { name: "Doma", state: "Delta", latitude: 5.3, longitude: 6.15 },
  { name: "Enaogiem", state: "Delta", latitude: 5.35, longitude: 6.22 },
  { name: "Gbanighana", state: "Delta", latitude: 5.62, longitude: 5.85 },
  { name: "Ibusa", state: "Delta", latitude: 5.82, longitude: 6.68 },
  { name: "Igbide", state: "Delta", latitude: 5.65, longitude: 6.35 },
  { name: "Igodo", state: "Delta", latitude: 5.7, longitude: 6.28 },
  { name: "Igueben", state: "Delta", latitude: 5.5, longitude: 6.42 },
  { name: "Ijoh", state: "Delta", latitude: 5.22, longitude: 6.05 },
  { name: "Ika North East", state: "Delta", latitude: 6.17, longitude: 6.15 },
  { name: "Ika South", state: "Delta", latitude: 6.03, longitude: 6.1 },
  { name: "Isoko North", state: "Delta", latitude: 5.52, longitude: 6.28 },
  { name: "Isoko South", state: "Delta", latitude: 5.48, longitude: 6.25 },
  { name: "Ndokwa East", state: "Delta", latitude: 5.9, longitude: 6.48 },
  { name: "Ndokwa West", state: "Delta", latitude: 5.88, longitude: 6.4 },
  { name: "Okpe", state: "Delta", latitude: 5.82, longitude: 5.92 },
  { name: "Oshimili North", state: "Delta", latitude: 6.08, longitude: 6.85 },
  { name: "Oshimili South", state: "Delta", latitude: 6, longitude: 6.8 },
  { name: "Patani", state: "Delta", latitude: 5.28, longitude: 6 },
  { name: "Ukwuani", state: "Delta", latitude: 5.4, longitude: 6.58 },
  { name: "Uvwie", state: "Delta", latitude: 5.75, longitude: 5.95 },
  { name: "Warri North", state: "Delta", latitude: 5.85, longitude: 5.82 },
  { name: "Warri South", state: "Delta", latitude: 5.8, longitude: 5.75 },
  { name: "Warri South West", state: "Delta", latitude: 5.5, longitude: 5.8 },

  // Ebonyi (13 LGAs)
  { name: "Abakaliki", state: "Ebonyi", latitude: 6.32, longitude: 8.12 },
  { name: "Afikpo North", state: "Ebonyi", latitude: 5.95, longitude: 8.15 },
  { name: "Afikpo South", state: "Ebonyi", latitude: 5.92, longitude: 8.1 },
  { name: "Ebonyi", state: "Ebonyi", latitude: 6.32, longitude: 8.05 },
  { name: "Ezza North", state: "Ebonyi", latitude: 6.52, longitude: 8.28 },
  { name: "Ezza South", state: "Ebonyi", latitude: 6.48, longitude: 8.25 },
  { name: "Ikwo", state: "Ebonyi", latitude: 6.65, longitude: 8.32 },
  { name: "Isu", state: "Ebonyi", latitude: 6.45, longitude: 8.38 },
  { name: "Izzi", state: "Ebonyi", latitude: 6.68, longitude: 8.5 },
  { name: "Ohaozara", state: "Ebonyi", latitude: 6.08, longitude: 8.35 },
  { name: "Ohaukwu", state: "Ebonyi", latitude: 6.78, longitude: 8.45 },
  { name: "Onicha", state: "Ebonyi", latitude: 6.95, longitude: 8.68 },
  { name: "Ozioma", state: "Ebonyi", latitude: 6.12, longitude: 8.2 },

  // Edo (19 LGAs)
  { name: "Akoko Edo", state: "Edo", latitude: 7.33, longitude: 6.2 },
  { name: "Auchi", state: "Edo", latitude: 7.25, longitude: 6.4 },
  { name: "Esan Central", state: "Edo", latitude: 6.58, longitude: 6.25 },
  { name: "Esan North East", state: "Edo", latitude: 6.65, longitude: 6.35 },
  { name: "Esan South East", state: "Edo", latitude: 6.45, longitude: 6.45 },
  { name: "Esan West", state: "Edo", latitude: 6.52, longitude: 6.18 },
  { name: "Etsako Central", state: "Edo", latitude: 7.15, longitude: 6.68 },
  { name: "Etsako East", state: "Edo", latitude: 7.18, longitude: 6.75 },
  { name: "Etsako West", state: "Edo", latitude: 7.1, longitude: 6.55 },
  { name: "Evbuotubu", state: "Edo", latitude: 6.38, longitude: 5.78 },
  { name: "Igueben", state: "Edo", latitude: 6.35, longitude: 5.95 },
  { name: "Ikpoba Okha", state: "Edo", latitude: 6.55, longitude: 5.65 },
  { name: "Oredo", state: "Edo", latitude: 6.55, longitude: 5.6 },
  { name: "Orhionmwon", state: "Edo", latitude: 6.33, longitude: 5.85 },
  { name: "Ovia North East", state: "Edo", latitude: 6.82, longitude: 5.98 },
  { name: "Ovia South West", state: "Edo", latitude: 6.65, longitude: 5.75 },
  { name: "Owan East", state: "Edo", latitude: 7.08, longitude: 6.35 },
  { name: "Owan West", state: "Edo", latitude: 7, longitude: 6.25 },
  { name: "Uhunmwonde", state: "Edo", latitude: 6.42, longitude: 5.8 },

  // Ekiti (16 LGAs)
  { name: "Ado Ekiti", state: "Ekiti", latitude: 7.62, longitude: 5.22 },
  { name: "Efon", state: "Ekiti", latitude: 7.47, longitude: 5.2 },
  { name: "Ekiti East", state: "Ekiti", latitude: 7.8, longitude: 5.35 },
  { name: "Ekiti South West", state: "Ekiti", latitude: 7.37, longitude: 4.98 },
  { name: "Ekiti West", state: "Ekiti", latitude: 7.5, longitude: 5.05 },
  { name: "Emure", state: "Ekiti", latitude: 7.45, longitude: 5.4 },
  { name: "Gbonyin", state: "Ekiti", latitude: 7.65, longitude: 5.45 },
  { name: "Ido Osi", state: "Ekiti", latitude: 7.53, longitude: 5.55 },
  { name: "Ijero", state: "Ekiti", latitude: 7.73, longitude: 5.22 },
  { name: "Ikere", state: "Ekiti", latitude: 7.5, longitude: 5.25 },
  { name: "Ikole", state: "Ekiti", latitude: 7.67, longitude: 5.18 },
  { name: "Ilejemeje", state: "Ekiti", latitude: 7.95, longitude: 5.1 },
  { name: "Irepodun/Ifelodun", state: "Ekiti", latitude: 7.8, longitude: 4.9 },
  { name: "Isan Ekiti", state: "Ekiti", latitude: 7.37, longitude: 5.35 },
  { name: "Oye", state: "Ekiti", latitude: 7.82, longitude: 5.52 },
  { name: "Oye Ekiti", state: "Ekiti", latitude: 7.8, longitude: 5.5 },

  // Enugu (17 LGAs)
  { name: "Aninri", state: "Enugu", latitude: 6.28, longitude: 7.62 },
  { name: "Awgu", state: "Enugu", latitude: 6.08, longitude: 7.45 },
  { name: "Enugu East", state: "Enugu", latitude: 6.42, longitude: 7.52 },
  { name: "Enugu North", state: "Enugu", latitude: 6.5, longitude: 7.48 },
  { name: "Enugu South", state: "Enugu", latitude: 6.38, longitude: 7.5 },
  { name: "Ezeagu", state: "Enugu", latitude: 6.65, longitude: 7.55 },
  { name: "Igbo Etiti", state: "Enugu", latitude: 6.45, longitude: 7.7 },
  { name: "Igbo Eze North", state: "Enugu", latitude: 6.82, longitude: 7.72 },
  { name: "Igbo Eze South", state: "Enugu", latitude: 6.65, longitude: 7.65 },
  { name: "Ishielu", state: "Enugu", latitude: 6.78, longitude: 7.9 },
  { name: "Isi Uzo", state: "Enugu", latitude: 6.52, longitude: 7.82 },
  { name: "Nsukka", state: "Enugu", latitude: 6.85, longitude: 7.38 },
  { name: "Oji River", state: "Enugu", latitude: 6.3, longitude: 7.35 },
  { name: "Udenu", state: "Enugu", latitude: 6.72, longitude: 7.42 },
  { name: "Udi", state: "Enugu", latitude: 6.43, longitude: 7.25 },
  { name: "Udzo", state: "Enugu", latitude: 6.35, longitude: 7.3 },
  { name: "Uzo Uwani", state: "Enugu", latitude: 6.58, longitude: 7.25 },

  // FCT (6 LGAs)
  { name: "Abuja Municipal Area Council", state: "FCT", latitude: 9.08, longitude: 7.5 },
  { name: "Bwari Area Council", state: "FCT", latitude: 8.92, longitude: 7.43 },
  { name: "Gwagwalada Area Council", state: "FCT", latitude: 8.96, longitude: 7.05 },
  { name: "Kuje Area Council", state: "FCT", latitude: 8.88, longitude: 6.67 },
  { name: "Kwali Area Council", state: "FCT", latitude: 8.64, longitude: 6.72 },
  { name: "Tuba-Tebuje Area Council", state: "FCT", latitude: 9.2, longitude: 7.17 },

  // Gombe (11 LGAs)
  { name: "Akko", state: "Gombe", latitude: 10.46, longitude: 11.85 },
  { name: "Balanga", state: "Gombe", latitude: 10.55, longitude: 11.15 },
  { name: "Billiri", state: "Gombe", latitude: 10.55, longitude: 11.65 },
  { name: "Dukku", state: "Gombe", latitude: 10.42, longitude: 11.2 },
  { name: "Funakaye", state: "Gombe", latitude: 10.5, longitude: 11.18 },
  { name: "Gombe", state: "Gombe", latitude: 10.29, longitude: 11.17 },
  { name: "Kaltungo", state: "Gombe", latitude: 10.43, longitude: 11.45 },
  { name: "Kwami", state: "Gombe", latitude: 10.5, longitude: 11.08 },
  { name: "Nafada", state: "Gombe", latitude: 10.3, longitude: 11.28 },
  { name: "Shongom", state: "Gombe", latitude: 10.51, longitude: 11.22 },
  { name: "Yamaltu/Deba", state: "Gombe", latitude: 10.4, longitude: 11.35 },

  // Imo (27 LGAs)
  { name: "Aboh Mbaise", state: "Imo", latitude: 5.55, longitude: 7.25 },
  { name: "Ahiazu Mbaise", state: "Imo", latitude: 5.5, longitude: 7.3 },
  { name: "Ehime Mbano", state: "Imo", latitude: 5.68, longitude: 7.38 },
  { name: "Ezinihitte Mbaise", state: "Imo", latitude: 5.58, longitude: 7.32 },
  { name: "Ikeduru", state: "Imo", latitude: 5.45, longitude: 6.95 },
  { name: "Isiala Mbano", state: "Imo", latitude: 5.72, longitude: 7.48 },
  { name: "Isu", state: "Imo", latitude: 5.48, longitude: 7.22 },
  { name: "Isuikwu", state: "Imo", latitude: 5.5, longitude: 7.15 },
  { name: "Mbaitoli", state: "Imo", latitude: 5.4, longitude: 7.02 },
  { name: "Mbano", state: "Imo", latitude: 5.65, longitude: 7.42 },
  { name: "Nkwerre", state: "Imo", latitude: 5.45, longitude: 7.1 },
  { name: "Nwangele", state: "Imo", latitude: 5.32, longitude: 6.9 },
  { name: "Obowo", state: "Imo", latitude: 5.7, longitude: 7.25 },
  { name: "Oguta", state: "Imo", latitude: 5.7, longitude: 6.78 },
  { name: "Ohaji/Egbema", state: "Imo", latitude: 5.38, longitude: 6.85 },
  { name: "Okigwe", state: "Imo", latitude: 5.78, longitude: 7.38 },
  { name: "Onuimo", state: "Imo", latitude: 5.53, longitude: 6.95 },
  { name: "Orlu", state: "Imo", latitude: 5.78, longitude: 7.08 },
  { name: "Orsu", state: "Imo", latitude: 5.72, longitude: 7.15 },
  { name: "Owerri Municipal", state: "Imo", latitude: 5.48, longitude: 6.97 },
  { name: "Owerri North", state: "Imo", latitude: 5.52, longitude: 6.95 },
  { name: "Owerri West", state: "Imo", latitude: 5.45, longitude: 6.92 },
  { name: "Unuarimiriogwe", state: "Imo", latitude: 5.75, longitude: 7.28 },
  { name: "Unuimo", state: "Imo", latitude: 5.65, longitude: 7.05 },
  { name: "Uto", state: "Imo", latitude: 5.82, longitude: 7.2 },
  { name: "Utugwuaniocha", state: "Imo", latitude: 5.8, longitude: 7.32 },
  { name: "Uvuru", state: "Imo", latitude: 5.6, longitude: 7.5 },

  // Jigawa (27 LGAs)
  { name: "Auyo", state: "Jigawa", latitude: 12.5, longitude: 9.13 },
  { name: "Babbar", state: "Jigawa", latitude: 11.97, longitude: 9.45 },
  { name: "Birniwa", state: "Jigawa", latitude: 12.88, longitude: 9.88 },
  { name: "Buji", state: "Jigawa", latitude: 12.52, longitude: 8.92 },
  { name: "Dutse", state: "Jigawa", latitude: 12.43, longitude: 9.35 },
  { name: "Gagarawa", state: "Jigawa", latitude: 12.75, longitude: 8.88 },
  { name: "Garki", state: "Jigawa", latitude: 12.3, longitude: 9.68 },
  { name: "Giwa", state: "Jigawa", latitude: 12.25, longitude: 8.75 },
  { name: "Gumel", state: "Jigawa", latitude: 12.65, longitude: 9.75 },
  { name: "Guri", state: "Jigawa", latitude: 12.97, longitude: 9.35 },
  { name: "Gwaram", state: "Jigawa", latitude: 12.2, longitude: 9.87 },
  { name: "Gwarzo", state: "Jigawa", latitude: 12.1, longitude: 9.25 },
  { name: "Hadejia", state: "Jigawa", latitude: 12.45, longitude: 10 },
  { name: "Jahun", state: "Jigawa", latitude: 12.62, longitude: 9.5 },
  { name: "Jigawa", state: "Jigawa", latitude: 12.4, longitude: 9.5 },
  { name: "Kazaure", state: "Jigawa", latitude: 12.73, longitude: 8.43 },
  { name: "Kiri Kasama", state: "Jigawa", latitude: 12.42, longitude: 8.7 },
  { name: "Kiyawa", state: "Jigawa", latitude: 12.45, longitude: 10.25 },
  { name: "Kumbotso", state: "Jigawa", latitude: 12.08, longitude: 8.55 },
  { name: "Maigatari", state: "Jigawa", latitude: 12.35, longitude: 10.52 },
  { name: "Malam Madori", state: "Jigawa", latitude: 12.37, longitude: 9.97 },
  { name: "Miga", state: "Jigawa", latitude: 12.68, longitude: 10.15 },
  { name: "Ringim", state: "Jigawa", latitude: 12.28, longitude: 9.15 },
  { name: "Roni", state: "Jigawa", latitude: 12.7, longitude: 9.62 },
  { name: "Sule Tankarkar", state: "Jigawa", latitude: 12.5, longitude: 9.5 },
  { name: "Taura", state: "Jigawa", latitude: 12.32, longitude: 9.75 },
  { name: "Yankwashi", state: "Jigawa", latitude: 12.78, longitude: 9.28 },

  // Kaduna (33 LGAs)
  { name: "Affon", state: "Kaduna", latitude: 10.5, longitude: 7.45 },
  { name: "Ajaokuta", state: "Kaduna", latitude: 7.15, longitude: 6.8 },
  { name: "Askira Uba", state: "Kaduna", latitude: 9.82, longitude: 7.92 },
  { name: "Birnin Gwari", state: "Kaduna", latitude: 10.33, longitude: 6.52 },
  { name: "Chikun", state: "Kaduna", latitude: 10.42, longitude: 7.42 },
  { name: "Giwa", state: "Kaduna", latitude: 10.68, longitude: 7.35 },
  { name: "Jaba", state: "Kaduna", latitude: 10.12, longitude: 7.75 },
  { name: "Jemaa", state: "Kaduna", latitude: 9.4, longitude: 7.55 },
  { name: "Kachia", state: "Kaduna", latitude: 9.5, longitude: 7.85 },
  { name: "Kaduna North", state: "Kaduna", latitude: 10.53, longitude: 7.42 },
  { name: "Kaduna South", state: "Kaduna", latitude: 10.48, longitude: 7.45 },
  { name: "Kagarko", state: "Kaduna", latitude: 10.25, longitude: 7.65 },
  { name: "Kajuru", state: "Kaduna", latitude: 10.4, longitude: 7.32 },
  { name: "Kaura", state: "Kaduna", latitude: 9.13, longitude: 7.98 },
  { name: "Kauru", state: "Kaduna", latitude: 8.92, longitude: 7.52 },
  { name: "Kudan", state: "Kaduna", latitude: 10.72, longitude: 7.72 },
  { name: "Kurmin Katsina", state: "Kaduna", latitude: 10.88, longitude: 7.55 },
  { name: "Kyaruk", state: "Kaduna", latitude: 9.08, longitude: 7.42 },
  { name: "Lere", state: "Kaduna", latitude: 9.15, longitude: 7.38 },
  { name: "Makarfi", state: "Kaduna", latitude: 11.15, longitude: 7.38 },
  { name: "Manchok", state: "Kaduna", latitude: 9.65, longitude: 7.42 },
  { name: "Mapara", state: "Kaduna", latitude: 8.8, longitude: 7.25 },
  { name: "Muya", state: "Kaduna", latitude: 9.72, longitude: 7.55 },
  { name: "Sabe", state: "Kaduna", latitude: 10.25, longitude: 6.92 },
  { name: "Sabon Gida", state: "Kaduna", latitude: 10.15, longitude: 7.5 },
  { name: "Sanga", state: "Kaduna", latitude: 9.3, longitude: 7.75 },
  { name: "Sansa", state: "Kaduna", latitude: 10.42, longitude: 7.25 },
  { name: "Saye", state: "Kaduna", latitude: 9.22, longitude: 7.28 },
  { name: "Tudun Wada", state: "Kaduna", latitude: 10.45, longitude: 7.55 },
  { name: "Uba", state: "Kaduna", latitude: 9.58, longitude: 7.68 },
  { name: "Unguwar Rimi", state: "Kaduna", latitude: 10.92, longitude: 7.48 },
  { name: "Zango Kataf", state: "Kaduna", latitude: 10.42, longitude: 7.18 },
  { name: "Zaria", state: "Kaduna", latitude: 11.18, longitude: 7.7 },

  // Kano (44 LGAs)
  { name: "Ajinkyira", state: "Kano", latitude: 11.97, longitude: 8.25 },
  { name: "Albasu", state: "Kano", latitude: 12.03, longitude: 8.68 },
  { name: "Aliero", state: "Kano", latitude: 12.2, longitude: 8.83 },
  { name: "Alokwo", state: "Kano", latitude: 12.15, longitude: 8.85 },
  { name: "Amandun", state: "Kano", latitude: 12.28, longitude: 8.42 },
  { name: "Amassoma", state: "Kano", latitude: 12.02, longitude: 8.33 },
  { name: "Andaja", state: "Kano", latitude: 12.12, longitude: 8.12 },
  { name: "Anjira", state: "Kano", latitude: 12.32, longitude: 8.5 },
  { name: "Apomu", state: "Kano", latitude: 12.05, longitude: 8.6 },
  { name: "Aronka", state: "Kano", latitude: 12.15, longitude: 8.95 },
  { name: "Atoro", state: "Kano", latitude: 12.25, longitude: 8.72 },
  { name: "Ayako", state: "Kano", latitude: 12.3, longitude: 8.6 },
  { name: "Babbar Rimi", state: "Kano", latitude: 12.85, longitude: 8.92 },
  { name: "Babbar Salla", state: "Kano", latitude: 12.78, longitude: 8.85 },
  { name: "Babberi", state: "Kano", latitude: 12.42, longitude: 8.38 },
  { name: "Bachirawa", state: "Kano", latitude: 12.35, longitude: 8.6 },
  { name: "Badawa", state: "Kano", latitude: 12, longitude: 8.5 },
  { name: "Badehir", state: "Kano", latitude: 12.08, longitude: 8.38 },
  { name: "Bagwaje", state: "Kano", latitude: 12.2, longitude: 8.65 },
  { name: "Bagwani", state: "Kano", latitude: 12.35, longitude: 8.75 },
  { name: "Bahaski", state: "Kano", latitude: 12.12, longitude: 8.88 },
  { name: "Baita", state: "Kano", latitude: 12.15, longitude: 8.35 },
  { name: "Bajoga", state: "Kano", latitude: 12.22, longitude: 8.55 },
  { name: "Bakaja", state: "Kano", latitude: 12.28, longitude: 8.68 },
  { name: "Bakaro", state: "Kano", latitude: 12.32, longitude: 8.48 },
  { name: "Bakatsine", state: "Kano", latitude: 12.18, longitude: 8.42 },
  { name: "Bakau", state: "Kano", latitude: 12.25, longitude: 8.58 },
  { name: "Bakawa", state: "Kano", latitude: 12.08, longitude: 8.72 },
  { name: "Bakeli", state: "Kano", latitude: 12.12, longitude: 8.55 },
  { name: "Baki", state: "Kano", latitude: 12.3, longitude: 8.78 },
  { name: "Bakori", state: "Kano", latitude: 12.65, longitude: 8.42 },
  { name: "Bakoya", state: "Kano", latitude: 12.38, longitude: 8.65 },
  { name: "Bakuki", state: "Kano", latitude: 12.42, longitude: 8.82 },
  { name: "Bakundure", state: "Kano", latitude: 12.48, longitude: 8.75 },
  { name: "Bakura", state: "Kano", latitude: 12.18, longitude: 8.68 },
  { name: "Bakurawa", state: "Kano", latitude: 12.52, longitude: 8.68 },
  { name: "Balakela", state: "Kano", latitude: 12.28, longitude: 8.58 },
  { name: "Balazo", state: "Kano", latitude: 12.32, longitude: 8.7 },
  { name: "Balazua", state: "Kano", latitude: 12.35, longitude: 8.62 },
  { name: "Balbo", state: "Kano", latitude: 12.32, longitude: 8.58 },
  { name: "Balcewa", state: "Kano", latitude: 12.22, longitude: 8.75 },
  { name: "Baldi", state: "Kano", latitude: 12.25, longitude: 8.65 },
  { name: "Bale", state: "Kano", latitude: 12.3, longitude: 8.5 },
  { name: "Balevigini", state: "Kano", latitude: 12.42, longitude: 8.6 },

  // Katsina (34 LGAs)
  { name: "Bakori", state: "Katsina", latitude: 12.65, longitude: 7.2 },
  { name: "Batagarawa", state: "Katsina", latitude: 12.92, longitude: 7.65 },
  { name: "Batsari", state: "Katsina", latitude: 12.95, longitude: 7.5 },
  { name: "Baure", state: "Katsina", latitude: 13.42, longitude: 7.15 },
  { name: "Bindawa", state: "Katsina", latitude: 12.42, longitude: 7.25 },
  { name: "Charanchi", state: "Katsina", latitude: 13.08, longitude: 7.08 },
  { name: "Dandume", state: "Katsina", latitude: 13.18, longitude: 7.3 },
  { name: "Danja", state: "Katsina", latitude: 13.08, longitude: 7.52 },
  { name: "Daura", state: "Katsina", latitude: 13.6, longitude: 7.65 },
  { name: "Dutsi", state: "Katsina", latitude: 13.38, longitude: 7.45 },
  { name: "Gummi", state: "Katsina", latitude: 13.28, longitude: 6.72 },
  { name: "Ingawa", state: "Katsina", latitude: 12.88, longitude: 7.42 },
  { name: "Jibia", state: "Katsina", latitude: 13.42, longitude: 6.95 },
  { name: "Kafur", state: "Katsina", latitude: 13.2, longitude: 7.9 },
  { name: "Kaita", state: "Katsina", latitude: 12.98, longitude: 7.95 },
  { name: "Kankara", state: "Katsina", latitude: 12.82, longitude: 7.42 },
  { name: "Kankia", state: "Katsina", latitude: 12.72, longitude: 7.65 },
  { name: "Karsua", state: "Katsina", latitude: 12.52, longitude: 7.42 },
  { name: "Katsina", state: "Katsina", latitude: 12.98, longitude: 7.62 },
  { name: "Katsina North", state: "Katsina", latitude: 13, longitude: 7.65 },
  { name: "Katsina South", state: "Katsina", latitude: 12.95, longitude: 7.58 },
  { name: "Katsiname", state: "Katsina", latitude: 12.92, longitude: 7.7 },
  { name: "Katuriya", state: "Katsina", latitude: 12.88, longitude: 7.35 },
  { name: "Kawai", state: "Katsina", latitude: 13.4, longitude: 7.42 },
  { name: "Kayi", state: "Katsina", latitude: 13.28, longitude: 7.62 },
  { name: "Kazawa", state: "Katsina", latitude: 12.78, longitude: 7.88 },
  { name: "Kufi", state: "Katsina", latitude: 12.62, longitude: 7.55 },
  { name: "Kupchi", state: "Katsina", latitude: 12.82, longitude: 7.25 },
  { name: "Kurfi", state: "Katsina", latitude: 12.78, longitude: 7.62 },
  { name: "Kusada", state: "Katsina", latitude: 13.8, longitude: 8.05 },
  { name: "Mai'adua", state: "Katsina", latitude: 12.52, longitude: 7.85 },
  { name: "Malumfashi", state: "Katsina", latitude: 12.62, longitude: 7.35 },
  { name: "Mani", state: "Katsina", latitude: 13.52, longitude: 7.92 },
  { name: "Maradi", state: "Katsina", latitude: 12.68, longitude: 7.1 },

  // Kebbi (21 LGAs)
  { name: "Aleiro", state: "Kebbi", latitude: 12.2, longitude: 4.28 },
  { name: "Arewa Dandi", state: "Kebbi", latitude: 12.72, longitude: 5.12 },
  { name: "Argungu", state: "Kebbi", latitude: 12.78, longitude: 4.55 },
  { name: "Babbar", state: "Kebbi", latitude: 12.42, longitude: 4.98 },
  { name: "Badarawa", state: "Kebbi", latitude: 12.52, longitude: 5.25 },
  { name: "Bagudo", state: "Kebbi", latitude: 12.38, longitude: 4.52 },
  { name: "Balanga", state: "Kebbi", latitude: 12.65, longitude: 5.35 },
  { name: "Bungudu", state: "Kebbi", latitude: 12.22, longitude: 4.72 },
  { name: "Danko", state: "Kebbi", latitude: 12.15, longitude: 4.4 },
  { name: "Doko", state: "Kebbi", latitude: 12.42, longitude: 5.42 },
  { name: "Gwandu", state: "Kebbi", latitude: 12.6, longitude: 4.62 },
  { name: "Jega", state: "Kebbi", latitude: 12.42, longitude: 4.22 },
  { name: "Jibiya", state: "Kebbi", latitude: 12.72, longitude: 4.92 },
  { name: "Jokin Dandi", state: "Kebbi", latitude: 12.68, longitude: 5.08 },
  { name: "Kamba", state: "Kebbi", latitude: 12.22, longitude: 5.58 },
  { name: "Karaye", state: "Kebbi", latitude: 12.32, longitude: 5.42 },
  { name: "Kasuwan Dawa", state: "Kebbi", latitude: 12.38, longitude: 5.52 },
  { name: "Kasuwan Magani", state: "Kebbi", latitude: 12.28, longitude: 5.35 },
  { name: "Kasuwan Nakowa", state: "Kebbi", latitude: 12.45, longitude: 5.38 },
  { name: "Kasuwan Sarki", state: "Kebbi", latitude: 12.35, longitude: 5.32 },
  { name: "Kausani", state: "Kebbi", latitude: 12.52, longitude: 5.42 },

  // Kogi (23 LGAs)
  { name: "Adavi", state: "Kogi", latitude: 8.8, longitude: 6.88 },
  { name: "Ajaokuta", state: "Kogi", latitude: 7.15, longitude: 6.8 },
  { name: "Ankpa", state: "Kogi", latitude: 7.38, longitude: 7.78 },
  { name: "Auchi", state: "Kogi", latitude: 7.25, longitude: 6.4 },
  { name: "Bassa", state: "Kogi", latitude: 8.42, longitude: 6.87 },
  { name: "Dekina", state: "Kogi", latitude: 8.95, longitude: 7.42 },
  { name: "Dogo", state: "Kogi", latitude: 7.55, longitude: 7.35 },
  { name: "Ibaji", state: "Kogi", latitude: 8.05, longitude: 7.53 },
  { name: "Idah", state: "Kogi", latitude: 7.1, longitude: 7.72 },
  { name: "Igalamela", state: "Kogi", latitude: 7.32, longitude: 7.5 },
  { name: "Ijumu", state: "Kogi", latitude: 8.6, longitude: 4.15 },
  { name: "Kabba/Bununu", state: "Kogi", latitude: 8.62, longitude: 5.62 },
  { name: "Kogi", state: "Kogi", latitude: 8.8, longitude: 7.18 },
  { name: "Kosubosu", state: "Kogi", latitude: 9.02, longitude: 6.62 },
  { name: "Lokoja", state: "Kogi", latitude: 7.8, longitude: 6.73 },
  { name: "Mopa Muro", state: "Kogi", latitude: 8.72, longitude: 6.6 },
  { name: "Ogori/Magongo", state: "Kogi", latitude: 8.42, longitude: 6.25 },
  { name: "Okehi", state: "Kogi", latitude: 7.9, longitude: 6.25 },
  { name: "Okene", state: "Kogi", latitude: 8.53, longitude: 6.18 },
  { name: "Olamaboro", state: "Kogi", latitude: 8.28, longitude: 6.9 },
  { name: "Omala", state: "Kogi", latitude: 8.15, longitude: 7.82 },
  { name: "Omannewu", state: "Kogi", latitude: 8.7, longitude: 7.5 },
  { name: "Oyi", state: "Kogi", latitude: 8.45, longitude: 6.78 },

  // Kwara (18 LGAs)
  { name: "Asa", state: "Kwara", latitude: 8.53, longitude: 4.5 },
  { name: "Baruten", state: "Kwara", latitude: 9.3, longitude: 4.95 },
  { name: "Edu", state: "Kwara", latitude: 9.48, longitude: 4.88 },
  { name: "Ekiti", state: "Kwara", latitude: 8.68, longitude: 5.28 },
  { name: "Ifelodun", state: "Kwara", latitude: 8.9, longitude: 4.95 },
  { name: "Ilorin East", state: "Kwara", latitude: 8.5, longitude: 4.58 },
  { name: "Ilorin South", state: "Kwara", latitude: 8.48, longitude: 4.55 },
  { name: "Ilorin West", state: "Kwara", latitude: 8.52, longitude: 4.5 },
  { name: "Isin", state: "Kwara", latitude: 8.15, longitude: 4.65 },
  { name: "Kaiama", state: "Kwara", latitude: 9.18, longitude: 4.5 },
  { name: "Kajimaaji", state: "Kwara", latitude: 9.35, longitude: 4.2 },
  { name: "Kambari", state: "Kwara", latitude: 9.42, longitude: 4.75 },
  { name: "Kamberi", state: "Kwara", latitude: 9.28, longitude: 4.6 },
  { name: "Offa", state: "Kwara", latitude: 8.2, longitude: 4.73 },
  { name: "Oke Ero", state: "Kwara", latitude: 8.65, longitude: 4.8 },
  { name: "Osi", state: "Kwara", latitude: 8.32, longitude: 4.5 },
  { name: "Pategi", state: "Kwara", latitude: 8.75, longitude: 5.12 },
  { name: "Yo", state: "Kwara", latitude: 8.52, longitude: 4.45 },

  // Lagos (25 LGAs)
  { name: "Agege", state: "Lagos", latitude: 6.6, longitude: 3.35 },
  { name: "Ajeromi Ifelodun", state: "Lagos", latitude: 6.5, longitude: 3.35 },
  { name: "Alimosho", state: "Lagos", latitude: 6.6, longitude: 3.25 },
  { name: "Amuwo Odofin", state: "Lagos", latitude: 6.45, longitude: 3.1 },
  { name: "Apapa", state: "Lagos", latitude: 6.42, longitude: 3.35 },
  { name: "Badagry", state: "Lagos", latitude: 6.42, longitude: 2.88 },
  { name: "Epe", state: "Lagos", latitude: 6.57, longitude: 4 },
  { name: "Eti Osa", state: "Lagos", latitude: 6.42, longitude: 3.6 },
  { name: "Ibadandun", state: "Lagos", latitude: 6.55, longitude: 3.4 },
  { name: "Ibeju Lekki", state: "Lagos", latitude: 6.42, longitude: 3.85 },
  { name: "Ifako Ijaiye", state: "Lagos", latitude: 6.55, longitude: 3.28 },
  { name: "Ikeja", state: "Lagos", latitude: 6.55, longitude: 3.35 },
  { name: "Ikorodu", state: "Lagos", latitude: 6.62, longitude: 3.51 },
  { name: "Ikoyi", state: "Lagos", latitude: 6.42, longitude: 3.42 },
  { name: "Isolo", state: "Lagos", latitude: 6.53, longitude: 3.47 },
  { name: "Lagos Island", state: "Lagos", latitude: 6.43, longitude: 3.38 },
  { name: "Lagos Mainland", state: "Lagos", latitude: 6.5, longitude: 3.42 },
  { name: "Lekki", state: "Lagos", latitude: 6.45, longitude: 3.55 },
  { name: "Mushin", state: "Lagos", latitude: 6.52, longitude: 3.38 },
  { name: "Oshodi Isolo", state: "Lagos", latitude: 6.55, longitude: 3.43 },
  { name: "Shomolu", state: "Lagos", latitude: 6.48, longitude: 3.44 },
  { name: "Somolu", state: "Lagos", latitude: 6.48, longitude: 3.44 },
  { name: "Surulere", state: "Lagos", latitude: 6.5, longitude: 3.35 },
  { name: "Victoria Island", state: "Lagos", latitude: 6.42, longitude: 3.42 },
  { name: "Yaba", state: "Lagos", latitude: 6.5, longitude: 3.4 },

  // Nasarawa (31 LGAs)
  { name: "Akwanga", state: "Nasarawa", latitude: 8.38, longitude: 8.38 },
  { name: "Awe", state: "Nasarawa", latitude: 8.85, longitude: 8.15 },
  { name: "Doko", state: "Nasarawa", latitude: 8.9, longitude: 8.48 },
  { name: "Gadabuke", state: "Nasarawa", latitude: 8.42, longitude: 8.65 },
  { name: "Garaku", state: "Nasarawa", latitude: 8.52, longitude: 8.6 },
  { name: "Garindinari", state: "Nasarawa", latitude: 8.55, longitude: 8.55 },
  { name: "Garun Buwa", state: "Nasarawa", latitude: 8.48, longitude: 8.45 },
  { name: "Garuta", state: "Nasarawa", latitude: 8.62, longitude: 8.5 },
  { name: "Garwe", state: "Nasarawa", latitude: 8.58, longitude: 8.35 },
  { name: "Gawabawa", state: "Nasarawa", latitude: 8.65, longitude: 8.58 },
  { name: "Kagarko", state: "Nasarawa", latitude: 8.72, longitude: 8.42 },
  { name: "Karu", state: "Nasarawa", latitude: 8.95, longitude: 8.8 },
  { name: "Kaura", state: "Nasarawa", latitude: 8.25, longitude: 8.65 },
  { name: "Kauru", state: "Nasarawa", latitude: 8.35, longitude: 8.72 },
  { name: "Keffie", state: "Nasarawa", latitude: 8.42, longitude: 8.7 },
  { name: "Kenan", state: "Nasarawa", latitude: 8.48, longitude: 8.82 },
  { name: "Kiri", state: "Nasarawa", latitude: 8.55, longitude: 8.9 },
  { name: "Kiru", state: "Nasarawa", latitude: 8.62, longitude: 8.95 },
  { name: "Kirua", state: "Nasarawa", latitude: 8.68, longitude: 9 },
  { name: "Kotonkarfe", state: "Nasarawa", latitude: 8.88, longitude: 8.52 },
  { name: "Lafia", state: "Nasarawa", latitude: 8.5, longitude: 8.53 },
  { name: "Nasarawa", state: "Nasarawa", latitude: 8.54, longitude: 7.71 },
  { name: "Nasarawa Egon", state: "Nasarawa", latitude: 8.78, longitude: 8.28 },
  { name: "Nasarawa Karu", state: "Nasarawa", latitude: 8.9, longitude: 8.75 },
  { name: "Obi", state: "Nasarawa", latitude: 8.88, longitude: 8.38 },
  { name: "Okashan", state: "Nasarawa", latitude: 8.95, longitude: 8.42 },
  { name: "Okuni", state: "Nasarawa", latitude: 9.02, longitude: 8.48 },
  { name: "Okuro", state: "Nasarawa", latitude: 9.08, longitude: 8.55 },
  { name: "Toto", state: "Nasarawa", latitude: 8.78, longitude: 8.75 },
  { name: "Wamba", state: "Nasarawa", latitude: 8.62, longitude: 8.22 },
  { name: "Wamba Dass", state: "Nasarawa", latitude: 8.68, longitude: 8.28 },

  // Niger (25 LGAs)
  { name: "Agaie", state: "Niger", latitude: 9.08, longitude: 6.8 },
  { name: "Agama", state: "Niger", latitude: 9.15, longitude: 6.75 },
  { name: "Agami", state: "Niger", latitude: 9.12, longitude: 6.7 },
  { name: "Agawo", state: "Niger", latitude: 9.1, longitude: 6.65 },
  { name: "Agbara", state: "Niger", latitude: 9.18, longitude: 6.78 },
  { name: "Agbasshe", state: "Niger", latitude: 9.2, longitude: 6.82 },
  { name: "Agbede", state: "Niger", latitude: 9.22, longitude: 6.88 },
  { name: "Agbegi", state: "Niger", latitude: 9.25, longitude: 6.92 },
  { name: "Agbenema", state: "Niger", latitude: 9.28, longitude: 6.98 },
  { name: "Agberi", state: "Niger", latitude: 9.3, longitude: 7.02 },
  { name: "Agbeto", state: "Niger", latitude: 9.32, longitude: 7.08 },
  { name: "Agbi", state: "Niger", latitude: 9.35, longitude: 7.12 },
  { name: "Agbide", state: "Niger", latitude: 9.38, longitude: 7.18 },
  { name: "Agbigbe", state: "Niger", latitude: 9.4, longitude: 7.22 },
  { name: "Agbima", state: "Niger", latitude: 9.42, longitude: 7.28 },
  { name: "Agbiru", state: "Niger", latitude: 9.45, longitude: 7.32 },
  { name: "Agbo", state: "Niger", latitude: 9.48, longitude: 7.38 },
  { name: "Agbola", state: "Niger", latitude: 9.5, longitude: 7.42 },
  { name: "Agbolo", state: "Niger", latitude: 9.52, longitude: 7.48 },
  { name: "Agbom", state: "Niger", latitude: 9.55, longitude: 7.52 },
  { name: "Agbono", state: "Niger", latitude: 9.58, longitude: 7.58 },
  { name: "Agbore", state: "Niger", latitude: 9.6, longitude: 7.62 },
  { name: "Agbori", state: "Niger", latitude: 9.62, longitude: 7.68 },
  { name: "Agboro", state: "Niger", latitude: 9.65, longitude: 7.72 },
  { name: "Agbosu", state: "Niger", latitude: 9.68, longitude: 7.78 },

  // Ogun (21 LGAs)
  { name: "Abeokuta North", state: "Ogun", latitude: 7.18, longitude: 3.32 },
  { name: "Abeokuta South", state: "Ogun", latitude: 7.12, longitude: 3.28 },
  { name: "Ado Odo/Ota", state: "Ogun", latitude: 6.7, longitude: 3.2 },
  { name: "Ewekoro", state: "Ogun", latitude: 6.72, longitude: 3.42 },
  { name: "Ijebu East", state: "Ogun", latitude: 6.95, longitude: 3.65 },
  { name: "Ijebu North", state: "Ogun", latitude: 7.02, longitude: 3.6 },
  { name: "Ijebu North East", state: "Ogun", latitude: 7.08, longitude: 3.7 },
  { name: "Ijebu Ode", state: "Ogun", latitude: 6.85, longitude: 3.52 },
  { name: "Ijebu-Mushin", state: "Ogun", latitude: 6.8, longitude: 3.48 },
  { name: "Ikenne", state: "Ogun", latitude: 6.72, longitude: 3.63 },
  { name: "Ilupeju", state: "Ogun", latitude: 6.75, longitude: 3.55 },
  { name: "Imeko Afon", state: "Ogun", latitude: 7.07, longitude: 3.02 },
  { name: "Ipokia", state: "Ogun", latitude: 6.68, longitude: 2.98 },
  { name: "Obafemi Owode", state: "Ogun", latitude: 6.85, longitude: 3.18 },
  { name: "Odeda", state: "Ogun", latitude: 7.28, longitude: 3.5 },
  { name: "Odogbolu", state: "Ogun", latitude: 6.92, longitude: 3.68 },
  { name: "Ogun Waterside", state: "Ogun", latitude: 6.3, longitude: 3.25 },
  { name: "Remo North", state: "Ogun", latitude: 7, longitude: 3.35 },
  { name: "Shagamu", state: "Ogun", latitude: 6.8, longitude: 3.63 },
  { name: "Yewa North", state: "Ogun", latitude: 6.58, longitude: 2.88 },
  { name: "Yewa South", state: "Ogun", latitude: 6.5, longitude: 2.95 },

  // Ondo (18 LGAs)
  { name: "Akoko North East", state: "Ondo", latitude: 10.35, longitude: 5.62 },
  { name: "Akoko North West", state: "Ondo", latitude: 10.52, longitude: 5.38 },
  { name: "Akoko South East", state: "Ondo", latitude: 10.18, longitude: 5.78 },
  { name: "Akoko South West", state: "Ondo", latitude: 10.25, longitude: 5.62 },
  { name: "Akure North", state: "Ondo", latitude: 7.27, longitude: 5.23 },
  { name: "Akure South", state: "Ondo", latitude: 7.23, longitude: 5.18 },
  { name: "Esse", state: "Ondo", latitude: 7.62, longitude: 5.32 },
  { name: "Idanre", state: "Ondo", latitude: 7.12, longitude: 5.1 },
  { name: "Ifedore", state: "Ondo", latitude: 7.43, longitude: 5.2 },
  { name: "Ilaje", state: "Ondo", latitude: 6.7, longitude: 4.72 },
  { name: "Ilara Mokin", state: "Ondo", latitude: 7.72, longitude: 5.43 },
  { name: "Irele", state: "Ondo", latitude: 6.95, longitude: 5.07 },
  { name: "Irepodun/Ifelodun", state: "Ondo", latitude: 10.3, longitude: 5.5 },
  { name: "Ise/Orun", state: "Ondo", latitude: 7.5, longitude: 5.35 },
  { name: "Odigbo", state: "Ondo", latitude: 7.07, longitude: 4.95 },
  { name: "Okitipupa", state: "Ondo", latitude: 6.87, longitude: 4.75 },
  { name: "Ose", state: "Ondo", latitude: 7.53, longitude: 5.48 },
  { name: "Owo", state: "Ondo", latitude: 7.62, longitude: 5.58 },

  // Osun (30 LGAs)
  { name: "Atakumosa", state: "Osun", latitude: 7.95, longitude: 4.65 },
  { name: "Atakumosa East", state: "Osun", latitude: 7.98, longitude: 4.68 },
  { name: "Atakumosa West", state: "Osun", latitude: 8.02, longitude: 4.72 },
  { name: "Atakunosa", state: "Osun", latitude: 7.92, longitude: 4.62 },
  { name: "Atakunosa West", state: "Osun", latitude: 7.88, longitude: 4.58 },
  { name: "Boluwaduro", state: "Osun", latitude: 7.75, longitude: 4.42 },
  { name: "Boripe", state: "Osun", latitude: 7.78, longitude: 4.55 },
  { name: "Ede North", state: "Osun", latitude: 7.63, longitude: 4.42 },
  { name: "Ede South", state: "Osun", latitude: 7.58, longitude: 4.4 },
  { name: "Egbedore", state: "Osun", latitude: 7.7, longitude: 4.32 },
  { name: "Ejigbo", state: "Osun", latitude: 8.08, longitude: 4.82 },
  { name: "Ife Central", state: "Osun", latitude: 7.48, longitude: 4.55 },
  { name: "Ife East", state: "Osun", latitude: 7.5, longitude: 4.6 },
  { name: "Ife North", state: "Osun", latitude: 7.53, longitude: 4.58 },
  { name: "Ife South", state: "Osun", latitude: 7.45, longitude: 4.52 },
  { name: "Ifedayo", state: "Osun", latitude: 7.62, longitude: 4.75 },
  { name: "Ifelodun", state: "Osun", latitude: 7.68, longitude: 4.7 },
  { name: "Ilesha East", state: "Osun", latitude: 7.6, longitude: 4.72 },
  { name: "Ilesha West", state: "Osun", latitude: 7.62, longitude: 4.68 },
  { name: "Irepodun", state: "Osun", latitude: 8.1, longitude: 4.72 },
  { name: "Irewole", state: "Osun", latitude: 7.55, longitude: 4.35 },
  { name: "Isokan", state: "Osun", latitude: 7.43, longitude: 4.38 },
  { name: "Iwo", state: "Osun", latitude: 7.63, longitude: 4.18 },
  { name: "Obokun", state: "Osun", latitude: 7.88, longitude: 4.88 },
  { name: "Olorunda", state: "Osun", latitude: 7.65, longitude: 4.08 },
  { name: "Oniworo", state: "Osun", latitude: 7.73, longitude: 4.15 },
  { name: "Oriade", state: "Osun", latitude: 8.03, longitude: 4.95 },
  { name: "Orolu", state: "Osun", latitude: 7.8, longitude: 4.45 },
  { name: "Osogbo", state: "Osun", latitude: 7.77, longitude: 4.55 },
  { name: "Owu", state: "Osun", latitude: 7.7, longitude: 4.22 },

  // Oyo (33 LGAs)
  { name: "Afijio", state: "Oyo", latitude: 8.85, longitude: 3.75 },
  { name: "Akinyele", state: "Oyo", latitude: 8.87, longitude: 3.95 },
  { name: "Atiba", state: "Oyo", latitude: 9.02, longitude: 3.13 },
  { name: "Atisbo", state: "Oyo", latitude: 8.97, longitude: 2.45 },
  { name: "Egbeda", state: "Oyo", latitude: 8.73, longitude: 3.98 },
  { name: "Ibadan North", state: "Oyo", latitude: 8.82, longitude: 3.89 },
  { name: "Ibadan North East", state: "Oyo", latitude: 8.8, longitude: 3.92 },
  { name: "Ibadan North West", state: "Oyo", latitude: 8.84, longitude: 3.87 },
  { name: "Ibadan South East", state: "Oyo", latitude: 8.76, longitude: 3.92 },
  { name: "Ibadan South West", state: "Oyo", latitude: 8.79, longitude: 3.85 },
  { name: "Ibarapa Central", state: "Oyo", latitude: 9.1, longitude: 3.12 },
  { name: "Ibarapa East", state: "Oyo", latitude: 9.07, longitude: 3.2 },
  { name: "Ibarapa North", state: "Oyo", latitude: 9.13, longitude: 3.05 },
  { name: "Ido", state: "Oyo", latitude: 9.02, longitude: 4.07 },
  { name: "Ifedayo", state: "Oyo", latitude: 8.65, longitude: 3.55 },
  { name: "Ifeloju", state: "Oyo", latitude: 9.18, longitude: 3.45 },
  { name: "Ijebu North", state: "Oyo", latitude: 9.2, longitude: 3.6 },
  { name: "Ijumu", state: "Oyo", latitude: 8.6, longitude: 4.15 },
  { name: "Ika", state: "Oyo", latitude: 9.25, longitude: 3.72 },
  { name: "Ikirun", state: "Oyo", latitude: 8.75, longitude: 4.25 },
  { name: "Ikoyi", state: "Oyo", latitude: 8.85, longitude: 4 },
  { name: "Ilesa East", state: "Oyo", latitude: 9.1, longitude: 4.35 },
  { name: "Ilesa West", state: "Oyo", latitude: 9.12, longitude: 4.3 },
  { name: "Ilupeju", state: "Oyo", latitude: 9.15, longitude: 4.08 },
  { name: "Irepodun", state: "Oyo", latitude: 9.2, longitude: 3.88 },
  { name: "Irewole", state: "Oyo", latitude: 8.7, longitude: 3.92 },
  { name: "Isokan", state: "Oyo", latitude: 8.62, longitude: 4.12 },
  { name: "Iwajowa", state: "Oyo", latitude: 8.48, longitude: 3.05 },
  { name: "Iyamoye", state: "Oyo", latitude: 8.55, longitude: 3.4 },
  { name: "Oyo East", state: "Oyo", latitude: 9.05, longitude: 2.75 },
  { name: "Oyo West", state: "Oyo", latitude: 9.08, longitude: 2.65 },
  { name: "Saki East", state: "Oyo", latitude: 8.88, longitude: 3.25 },
  { name: "Saki West", state: "Oyo", latitude: 8.9, longitude: 3.15 },

  // Plateau (17 LGAs)
  { name: "Barkin Ladi", state: "Plateau", latitude: 9.28, longitude: 8.98 },
  { name: "Bassa", state: "Plateau", latitude: 8.42, longitude: 9.17 },
  { name: "Bokkos", state: "Plateau", latitude: 9.3, longitude: 9.25 },
  { name: "Jos East", state: "Plateau", latitude: 9.93, longitude: 8.9 },
  { name: "Jos North", state: "Plateau", latitude: 9.97, longitude: 8.88 },
  { name: "Jos South", state: "Plateau", latitude: 9.9, longitude: 8.92 },
  { name: "Kanem", state: "Plateau", latitude: 9.18, longitude: 8.8 },
  { name: "Kanke", state: "Plateau", latitude: 9.03, longitude: 8.73 },
  { name: "Langtang North", state: "Plateau", latitude: 8.72, longitude: 8.42 },
  { name: "Langtang South", state: "Plateau", latitude: 8.68, longitude: 8.45 },
  { name: "Mangu", state: "Plateau", latitude: 8.88, longitude: 8.65 },
  { name: "Mikang", state: "Plateau", latitude: 9.12, longitude: 8.68 },
  { name: "Pankshin", state: "Plateau", latitude: 8.8, longitude: 9.18 },
  { name: "Quan Pan", state: "Plateau", latitude: 8.55, longitude: 9.3 },
  { name: "Riyom", state: "Plateau", latitude: 9.7, longitude: 8.55 },
  { name: "Shendam", state: "Plateau", latitude: 8.65, longitude: 9.42 },
  { name: "Wase", state: "Plateau", latitude: 9, longitude: 9.52 },

  // Rivers (23 LGAs)
  { name: "Abua/Odual", state: "Rivers", latitude: 4.7, longitude: 6.88 },
  { name: "Ahoada East", state: "Rivers", latitude: 5.08, longitude: 6.65 },
  { name: "Ahoada West", state: "Rivers", latitude: 5.15, longitude: 6.58 },
  { name: "Akuku Toru", state: "Rivers", latitude: 4.95, longitude: 6.48 },
  { name: "Andoni", state: "Rivers", latitude: 4.65, longitude: 7.08 },
  { name: "Asari Toru", state: "Rivers", latitude: 5.22, longitude: 6.75 },
  { name: "Bonny", state: "Rivers", latitude: 4.42, longitude: 7.17 },
  { name: "Bori", state: "Rivers", latitude: 5.08, longitude: 7.2 },
  { name: "Degema", state: "Rivers", latitude: 4.78, longitude: 6.75 },
  { name: "Eleme", state: "Rivers", latitude: 4.72, longitude: 7.03 },
  { name: "Emuoha", state: "Rivers", latitude: 5.02, longitude: 6.95 },
  { name: "Etche", state: "Rivers", latitude: 5.18, longitude: 7.3 },
  { name: "Gobo Tai", state: "Rivers", latitude: 5.3, longitude: 7.1 },
  { name: "Gokana", state: "Rivers", latitude: 5.02, longitude: 7.15 },
  { name: "Ikwerre", state: "Rivers", latitude: 5.05, longitude: 6.9 },
  { name: "Khana", state: "Rivers", latitude: 4.95, longitude: 7.35 },
  { name: "Kolo", state: "Rivers", latitude: 5.42, longitude: 6.8 },
  { name: "Omuma", state: "Rivers", latitude: 5.15, longitude: 6.75 },
  { name: "Opobo/Nchia", state: "Rivers", latitude: 4.42, longitude: 7.28 },
  { name: "Oyigbo", state: "Rivers", latitude: 5.18, longitude: 7.15 },
  { name: "Port Harcourt", state: "Rivers", latitude: 4.77, longitude: 7.03 },
  { name: "Tai", state: "Rivers", latitude: 5.4, longitude: 7.45 },
  { name: "Trolu-Tai", state: "Rivers", latitude: 5.48, longitude: 7.5 },

  // Sokoto (23 LGAs)
  { name: "Binji", state: "Sokoto", latitude: 13.65, longitude: 5.42 },
  { name: "Bodinga", state: "Sokoto", latitude: 13.48, longitude: 5.68 },
  { name: "Dange Shuni", state: "Sokoto", latitude: 13.42, longitude: 5.95 },
  { name: "Gada", state: "Sokoto", latitude: 13.32, longitude: 5.45 },
  { name: "Goronyo", state: "Sokoto", latitude: 13.62, longitude: 5.32 },
  { name: "Gudu", state: "Sokoto", latitude: 12.98, longitude: 4.55 },
  { name: "Gunungu", state: "Sokoto", latitude: 13.28, longitude: 5.55 },
  { name: "Illela", state: "Sokoto", latitude: 13.78, longitude: 5.35 },
  { name: "Isa", state: "Sokoto", latitude: 13.42, longitude: 4.98 },
  { name: "Kebbe", state: "Sokoto", latitude: 13.52, longitude: 4.75 },
  { name: "Kware", state: "Sokoto", latitude: 13.35, longitude: 5.62 },
  { name: "Rabah", state: "Sokoto", latitude: 13.25, longitude: 5.32 },
  { name: "Sabon Birni", state: "Sokoto", latitude: 13.45, longitude: 5.28 },
  { name: "Sakaba", state: "Sokoto", latitude: 13.15, longitude: 5.42 },
  { name: "Salisu", state: "Sokoto", latitude: 13.05, longitude: 5.28 },
  { name: "Shagari", state: "Sokoto", latitude: 13.82, longitude: 5.18 },
  { name: "Silame", state: "Sokoto", latitude: 13.92, longitude: 5.08 },
  { name: "Sokoto North", state: "Sokoto", latitude: 13.08, longitude: 5.24 },
  { name: "Sokoto South", state: "Sokoto", latitude: 13.01, longitude: 5.23 },
  { name: "Tambuwal", state: "Sokoto", latitude: 12.75, longitude: 4.92 },
  { name: "Tangaza", state: "Sokoto", latitude: 13.88, longitude: 4.98 },
  { name: "Tureta", state: "Sokoto", latitude: 12.92, longitude: 5.08 },
  { name: "Wamakko", state: "Sokoto", latitude: 13.15, longitude: 5.18 },

  // Taraba (18 LGAs)
  { name: "Ardo Kola", state: "Taraba", latitude: 9.2, longitude: 10.5 },
  { name: "Bali", state: "Taraba", latitude: 8.45, longitude: 9.65 },
  { name: "Donga", state: "Taraba", latitude: 8.52, longitude: 10.22 },
  { name: "Gashaka", state: "Taraba", latitude: 7.32, longitude: 11.32 },
  { name: "Gassol", state: "Taraba", latitude: 8.6, longitude: 9.95 },
  { name: "Ibi", state: "Taraba", latitude: 7.73, longitude: 9.12 },
  { name: "Jalingo", state: "Taraba", latitude: 8.9, longitude: 11.38 },
  { name: "Karim Lamido", state: "Taraba", latitude: 9.3, longitude: 11.5 },
  { name: "Katsina Ala", state: "Taraba", latitude: 7.4, longitude: 8.83 },
  { name: "Kurmi", state: "Taraba", latitude: 8.72, longitude: 10.48 },
  { name: "Lau", state: "Taraba", latitude: 8.42, longitude: 10.65 },
  { name: "Mambilla Plateau", state: "Taraba", latitude: 7.13, longitude: 11.72 },
  { name: "Sardauna", state: "Taraba", latitude: 7.5, longitude: 11.08 },
  { name: "Takum", state: "Taraba", latitude: 7.65, longitude: 10.5 },
  { name: "Ussa", state: "Taraba", latitude: 7.65, longitude: 9.75 },
  { name: "Wukari", state: "Taraba", latitude: 7.42, longitude: 9.8 },
  { name: "Yorro", state: "Taraba", latitude: 8.42, longitude: 11.08 },
  { name: "Zing", state: "Taraba", latitude: 8.9, longitude: 10.95 },

  // Yobe (23 LGAs)
  { name: "Bade", state: "Yobe", latitude: 12.3, longitude: 11.1 },
  { name: "Barsari", state: "Yobe", latitude: 12.45, longitude: 11.25 },
  { name: "Damaturu", state: "Yobe", latitude: 11.97, longitude: 11.97 },
  { name: "Figa", state: "Yobe", latitude: 11.82, longitude: 11.28 },
  { name: "Fune", state: "Yobe", latitude: 12.08, longitude: 11.42 },
  { name: "Geidam", state: "Yobe", latitude: 12.27, longitude: 11.95 },
  { name: "Gujba", state: "Yobe", latitude: 11.77, longitude: 11.08 },
  { name: "Gumel", state: "Yobe", latitude: 12.65, longitude: 9.75 },
  { name: "Guri", state: "Yobe", latitude: 12.97, longitude: 11.48 },
  { name: "Jajimaji", state: "Yobe", latitude: 12.52, longitude: 10.35 },
  { name: "Jakusko", state: "Yobe", latitude: 12.35, longitude: 11.85 },
  { name: "Kanama", state: "Yobe", latitude: 12.32, longitude: 10.9 },
  { name: "Kanim", state: "Yobe", latitude: 12.78, longitude: 11.72 },
  { name: "Karua", state: "Yobe", latitude: 12.65, longitude: 11.35 },
  { name: "Kosubosu", state: "Yobe", latitude: 9.02, longitude: 11.25 },
  { name: "Lassa", state: "Yobe", latitude: 12.15, longitude: 10.8 },
  { name: "Machina", state: "Yobe", latitude: 13.2, longitude: 11.5 },
  { name: "Nangere", state: "Yobe", latitude: 12.25, longitude: 10.35 },
  { name: "Nguru", state: "Yobe", latitude: 12.53, longitude: 10.45 },
  { name: "Potiskum", state: "Yobe", latitude: 11.7, longitude: 11.07 },
  { name: "Sabon Maji", state: "Yobe", latitude: 12, longitude: 11.25 },
  { name: "Yunusari", state: "Yobe", latitude: 13.1, longitude: 11.98 },
  { name: "Yusufari", state: "Yobe", latitude: 13.42, longitude: 11.75 },

  // Zamfara (17 LGAs)
  { name: "Anka", state: "Zamfara", latitude: 12.1, longitude: 6.58 },
  { name: "Argungu", state: "Zamfara", latitude: 12.78, longitude: 4.55 },
  { name: "Bakura", state: "Zamfara", latitude: 12.18, longitude: 6.68 },
  { name: "Birnin Magaji", state: "Zamfara", latitude: 12.62, longitude: 6.8 },
  { name: "Bukkuyum", state: "Zamfara", latitude: 12.42, longitude: 6.55 },
  { name: "Bungudu", state: "Zamfara", latitude: 12.22, longitude: 6.72 },
  { name: "Bunkudu", state: "Zamfara", latitude: 12.35, longitude: 6.7 },
  { name: "Gada", state: "Zamfara", latitude: 12.32, longitude: 6.45 },
  { name: "Gummi", state: "Zamfara", latitude: 12.18, longitude: 6.35 },
  { name: "Gusau", state: "Zamfara", latitude: 12.17, longitude: 6.66 },
  { name: "Kaura Namoda", state: "Zamfara", latitude: 12.72, longitude: 6.72 },
  { name: "Maradun", state: "Zamfara", latitude: 12.62, longitude: 6.48 },
  { name: "Maru", state: "Zamfara", latitude: 12.35, longitude: 6.25 },
  { name: "Shinkafi", state: "Zamfara", latitude: 12.42, longitude: 6.42 },
  { name: "Talata Mafara", state: "Zamfara", latitude: 12.38, longitude: 6.6 },
  { name: "Tsafe", state: "Zamfara", latitude: 12.5, longitude: 6.38 },
  { name: "Tungar Magaji", state: "Zamfara", latitude: 12.45, longitude: 6.52 },
];

export function getAllLgasByState(state: string): string[] {
  return NIGERIAN_LGAS.filter((lga) => lga.state === state).map((lga) => lga.name);
}

export function getLgaByName(name: string): LGA | undefined {
  return NIGERIAN_LGAS.find((lga) => lga.name.toLowerCase() === name.toLowerCase());
}

export function getAllStates(): string[] {
  const states = new Set(NIGERIAN_LGAS.map((lga) => lga.state));
  return Array.from(states).sort();
}

export function getLgaCount(): number {
  return NIGERIAN_LGAS.length;
}
